### ISSUE TITLE
I have some puzzling bugs, do you know how to solve it?

### ISSUE THREAD

**Issue by acfqcd** [luoao-kddi/SCP#2]
I'm using the ckpt files you provided for the octattention and kitti datasets, but I'm running encoder.py and encountering . /.hydra file directory problem, the file directory you provided does not have the relevant files.
sorry for the intrusion.

raise MissingConfigException(
hydra.errors.MissingConfigException: Primary config directory not found.
Check that the config directory 'xxx/scp_octattn_kitti./.hydra' exists and readable

**Comment by luoao-kddi** [comment]
Hi, thank you for being interested in our work.

Sorry we forgot to upload all the information about the ckpt before. Now the .hydra folder has been uploaded to the google drive, please check it.
