### ISSUE TITLE
About configurable files in KITTI

### ISSUE THREAD

**Issue by sz3623** [luoao-kddi/SCP#3]
Inspiring work! There is a question about the KITTI dataset. Would you mind providing information about the coordinate accuracy of different sequences in KITTI, and configurable files for octree and prediction tree modes in GPCC at different quantization step parameters?

**Comment by luoao-kddi** [comment]
Thanks for your interest.
However, we directly copied the G-PCC results from the EHEM paper. If you want to generate the result by yourself, please get in touch with them and ask for the details.
