### ISSUE TITLE
No module named 'transformers'

### ISSUE THREAD

**Issue by RuixiangXue** [luoao-kddi/SCP#5]
When I run the encode.py to conduct eval, the error comes: 

from transformers.activations import ACT2FN
ModuleNotFoundError: No module named 'transformers'".

I wonder is this a package ? because I did not found relevant file named "transformer.py"

**Comment by luoao-kddi** [comment]
Oh, I forgot to put it in the requirements.txt. It is a library from HuggingFace. You can directly install it by `pip install transformers`.
